FROM golang:1.18.1-alpine3.14 AS builder
WORKDIR /app
COPY . .
RUN go build -o broker main.go

FROM alpine:3.14
WORKDIR /app
COPY --from=builder /app/broker .

EXPOSE 8000 9000
CMD [ "/app/broker" ]